bump Guice dependency version from 4.1.0 to 4.2.0
see https://github.com/google/guice/wiki/Guice42

Also remove explicit Guava dependency, it's better to just transitively
inherit the version which Guice requires instead of forcing our own
version 19.0, because the Guice bump from 4.1.0 to 4.2.0 required a
newer Guava version, and lead to this error with a fixed older Guava
version:

java.lang.NoSuchMethodError:
com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
	at com.google.inject.TypeLiteral.getParameterTypes(TypeLiteral.java:278)